# freeling

FROM debian:stretch

MAINTAINER Hernán 'herchu' Foffani <hfoffani@gmail.com>


RUN apt-get update -qq && apt-get install -y -qq \
    locales \
    libboost-regex-dev \
    libicu-dev \
    zlib1g-dev \
    libboost-system-dev \
    libboost-program-options-dev \
    libboost-thread-dev \
    libboost-filesystem-dev


RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    locale-gen en_US.UTF-8 && \
    /usr/sbin/update-locale LANG=en_US.UTF-8

ENV LC_ALL en_US.UTF-8




RUN apt-get update -qq && apt-get install -y -qq \
    build-essential \
    swig \
    python3-dev 



# For building test you can use a local .deb package.
ADD https://github.com/TALP-UPC/FreeLing/releases/download/4.1/freeling-4.1-stretch-amd64.deb freeling4.deb
# ADD freeling-4.1-stretch-amd64.deb

RUN dpkg -i freeling4.deb \
    && rm freeling4.deb


RUN ls -d /usr/share/freeling/?? | egrep -v es | xargs rm -rf 




COPY APIs/ /home/APIs

RUN cd /home/APIs/python3 && \
    sed -e 's=/usr/local=/usr=' \
        -e 's=\["es"."ca"."en"."it"]=["es"]=' \
        -i sample.py && \
    make


